### YamlMime:Yaml
ms.openlocfilehash: 7a9b8b6a61279810796f347f52f339e740ba8c2c
ms.sourcegitcommit: e5257bdb021745329530b88730018d62dabf3479
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 04/15/2022
ms.locfileid: "145884079"
changelog:
  exclude:
    labels:
    - ignore-for-release
    authors:
    - octocat
  categories:
  - title: "破壊的変更 \U0001F6E0"
    labels:
    - Semver-Major
    - breaking-change
  - title: "魅力的な新機能 \U0001F389"
    labels:
    - Semver-Minor
    - enhancement
  - title: その他の変更
    labels:
    - '*'
